name: Build and Test Docker Images.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component:
          - frontend
          - backend
          - database

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image for ${{ matrix.component }}
        run: |
          docker build -t myapp-${{ matrix.component }} ./${{ matrix.component }}

      - name: Run Tests for ${{ matrix.component }}
        run: |
          # Rodar os testes para o componente
          docker run myapp-${{ matrix.component }} npm test

