name: Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-frontend ./frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-backend ./backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-database ./database

          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-backend
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-database

      - name: Simulate Deploy to Production
        run: |
          echo "Deploying to production..."
          # Simulação do deploy (aqui você pode rodar comandos específicos para seu ambiente de produção)
